### ISSUE TITLE
Formatting sometimes erases file contents

### ISSUE THREAD

**Issue by webthethird** [rmcmk/forge-format-vsc#2]
I am not sure how to reproduce this yet. I use format on save in VSC and just switched to this formatter, but quickly noticed that sometimes when I save it deletes all of my code! 

It doesn't seem to always happen, though when it does, it is consistent. In my limited observation, the formatter worked fine for a few hours, then seemed to have trouble formatting the file when I tried to save with an unfinished line of code. It seemed to be fine once I finished the line, but not long after it started uniformly erasing the contents of any Solidity file I tried to save. All of this could be undone with a few ctrl+z, but ultimately I had to turn off format on save until I find an alternative.

**Comment by rmcmk** [comment]
Hey thanks for reaching out. Yeah, I have experienced this a few times myself, and another issue was opened #1 and I couldn't get anywhere with his reproduction. It is seemingly erratic. I'll give it another look this weekend.

**Comment by xlab** [comment]
I just installed and it really just deletes the contents. From the console `forge fmt` on the file works fine.

Look, there is no other formatter that deletes the contents :D At least it could have it not formatted.

**Comment by xlab** [comment]
It's also okay to delete this plugin from the marketplace, it kinda doesn't contribute to the ecosystem in a positive way.

**Comment by rmcmk** [comment]
> It's also okay to delete this plugin from the marketplace, it kinda doesn't contribute to the ecosystem in a positive way.

@xlab I went ahead and removed it, thanks for pointing that out. I initially created this out of frustration with other tooling conflicts with Foundry, but I've since shifted focus to a new project, so this has been neglected as my time with Solidity has dropped off this year. Appreciate you giving it a try and for the feedback—sorry for being a crappy maintainer, LOL. It’s been about a year since I was really active in the Sol space; hopefully, the tooling has improved by the time I get back into the ecosystem.
